name: deploy

on:
  push:
    tags:
      - "v2*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: pnpm

      - run: pnpm i

      - run: pnpm run build

      - run: |
          mkdir dist/dist
          mv dist/index.js dist/dist/index.js
          cp action.yml dist

      - run: echo "TAG=v$(cat package.json | jq .version -r)" >> $GITHUB_ENV

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: deploy ${{ github.ref }}
          publish_branch: dist/v2
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          tag_name: dist/${{ env.TAG }}
          tag_message: "release ${{ github.ref_name }}"

      - run: gh release create "dist/${TAG}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
