name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - dev
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        id: restore-cache
        with:
          path: |
            ./node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
        if: steps.restore-cache.outputs.cache-hit != 'true'
      - run: npm run all

  test-run: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        extras: [group1, group2]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "::add-path::$HOME/.poetry/bin"

      - uses: ./
        with:
          extras: |
            ${{ matrix.extras }}

      - run: python tests/${{ matrix.extras }}.py

      - run: pre-commit --version
        if: "${{ matrix.extras == 'group2' }}"


  test-multi-group: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "::add-path::$HOME/.poetry/bin"

      - uses: ./
        with:
          extras: |
            group1
            group2

      - run: python tests/group1.py
      - run: python tests/group2.py
      - run: pre-commit --version
